swagger: '2.0'
info:
  version: '1.0'
  title: weTron API
host: 'localhost:8080'
basePath: /api
tags:
  - name: games
schemes:
  - http
paths:
  /games:
    get:
      tags:
        - games
      summary: Spiele abfragen
      description: Liefert alle offenen Spiele zurück
      operationId: getAllGames
      consumes:
        - application/json
      produces:
        - application/json
      parameters: []
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Game'
    post:
      tags:
        - games
      summary: Spiel anlegen
      description: Legt ein neues Spiel an.
      operationId: createGame
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Anzulegendes Spiel
          required: true
          schema:
            $ref: '#/definitions/Game'
      responses:
        default:
          description: successful operation
  '/games/{id}':
    get:
      tags:
        - games
      summary: Spiel ansehen
      description: Liefert Informationen zu einem bestimmten Spiel zurück.
      operationId: getGame
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: Id des Spiels
          required: true
          type: integer
          format: int32
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Game'
definitions:
  Game:
    type: object
    properties:
      id:
        type: integer
        format: int32
      name:
        type: string